/*
 * Midimon.
 * Copyright (C) 2018-2019  Vilniaus Blokas UAB, https://blokas.io/midiboy
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 of the
 * License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <avr/pgmspace.h>

// Font data based on X11 micro which is available as Public Domain font: https://github.com/olikraus/u8g2/wiki/fntgrpx11#micro
// https://cgit.freedesktop.org/xorg/font/micro-misc/tree/COPYING

#define FONT_Y_OFFSET 1

const PROGMEM unsigned char MICRO_FONT[288] = {
	0x00 << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x1D << FONT_Y_OFFSET, 0x1D << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x18 << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET, 0x18 << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x0A << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x0D << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x0B << FONT_Y_OFFSET,
	0x16 << FONT_Y_OFFSET, 0x0C << FONT_Y_OFFSET, 0x1A << FONT_Y_OFFSET,
	0x06 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET,
	0x00 << FONT_Y_OFFSET, 0x08 << FONT_Y_OFFSET, 0x18 << FONT_Y_OFFSET,
	0x00 << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET,
	0x11 << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x15 << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET,
	0x04 << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET,
	0x01 << FONT_Y_OFFSET, 0x03 << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x04 << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET,
	0x01 << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x01 << FONT_Y_OFFSET, 0x06 << FONT_Y_OFFSET, 0x18 << FONT_Y_OFFSET,
	0x0E << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET,
	0x08 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x13 << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET,
	0x11 << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x1E << FONT_Y_OFFSET, 0x02 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1D << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x12 << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x17 << FONT_Y_OFFSET,
	0x10 << FONT_Y_OFFSET, 0x13 << FONT_Y_OFFSET, 0x1C << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1D << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x1E << FONT_Y_OFFSET,
	0x1B << FONT_Y_OFFSET, 0x1B << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x19 << FONT_Y_OFFSET, 0x1B << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x04 << FONT_Y_OFFSET, 0x0A << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET,
	0x0A << FONT_Y_OFFSET, 0x0A << FONT_Y_OFFSET, 0x0A << FONT_Y_OFFSET,
	0x11 << FONT_Y_OFFSET, 0x0A << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET,
	0x10 << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x1C << FONT_Y_OFFSET,
	0x0E << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x19 << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x14 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x1B << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x14 << FONT_Y_OFFSET, 0x14 << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET, 0x17 << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x11 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET,
	0x03 << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET, 0x1B << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x08 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x10 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x14 << FONT_Y_OFFSET, 0x1C << FONT_Y_OFFSET,
	0x1E << FONT_Y_OFFSET, 0x13 << FONT_Y_OFFSET, 0x1D << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x14 << FONT_Y_OFFSET, 0x1B << FONT_Y_OFFSET,
	0x1D << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x17 << FONT_Y_OFFSET,
	0x10 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x10 << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1E << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET, 0x1E << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x02 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x1B << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET, 0x1B << FONT_Y_OFFSET,
	0x1C << FONT_Y_OFFSET, 0x07 << FONT_Y_OFFSET, 0x1C << FONT_Y_OFFSET,
	0x13 << FONT_Y_OFFSET, 0x15 << FONT_Y_OFFSET, 0x19 << FONT_Y_OFFSET,
	0x00 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET,
	0x18 << FONT_Y_OFFSET, 0x06 << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET,
	0x11 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x08 << FONT_Y_OFFSET, 0x10 << FONT_Y_OFFSET, 0x08 << FONT_Y_OFFSET,
	0x01 << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET,
	0x00 << FONT_Y_OFFSET, 0x18 << FONT_Y_OFFSET, 0x08 << FONT_Y_OFFSET,
	0x0B << FONT_Y_OFFSET, 0x0D << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x0B << FONT_Y_OFFSET, 0x0D << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x14 << FONT_Y_OFFSET, 0x10 << FONT_Y_OFFSET,
	0x0D << FONT_Y_OFFSET, 0x0B << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x08 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x00 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x03 << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x1F << FONT_Y_OFFSET, 0x06 << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET,
	0x10 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x08 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x0A << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET,
	0x0E << FONT_Y_OFFSET, 0x0A << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x08 << FONT_Y_OFFSET, 0x0C << FONT_Y_OFFSET,
	0x0D << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET, 0x0B << FONT_Y_OFFSET,
	0x08 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x0E << FONT_Y_OFFSET, 0x01 << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET,
	0x0F << FONT_Y_OFFSET, 0x02 << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET,
	0x09 << FONT_Y_OFFSET, 0x06 << FONT_Y_OFFSET, 0x09 << FONT_Y_OFFSET,
	0x0D << FONT_Y_OFFSET, 0x03 << FONT_Y_OFFSET, 0x0E << FONT_Y_OFFSET,
	0x0B << FONT_Y_OFFSET, 0x0F << FONT_Y_OFFSET, 0x0D << FONT_Y_OFFSET,
	0x04 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x11 << FONT_Y_OFFSET,
	0x00 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x00 << FONT_Y_OFFSET,
	0x11 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET,
	0x08 << FONT_Y_OFFSET, 0x0C << FONT_Y_OFFSET, 0x04 << FONT_Y_OFFSET,
	0x01 << FONT_Y_OFFSET, 0x1F << FONT_Y_OFFSET, 0x10 << FONT_Y_OFFSET,
};
